<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<nav id="intro" class="container">
  <div class="row">
    <div class="col-xs-4">
      <div class="btn-container">
        <a class="btn home-button" href="<?=$this->url('browse-home')?>">
          <div class="icon">
            <span class="fa fa-search fa-7x"></span>
          </div>
          <span class="btn-txt">Browse Catalog</span>
        </a>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="btn-container">
        <a class="btn home-button" href="<?=$this->url('alphabrowse-home')?>">
          <div class="icon">
            <span class="fa fa-font fa-7x"></span>
          </div>
          <span class="btn-txt">Browse Alphabetically</span>
        </a>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="btn-container">
        <a class="btn home-button" href="http://www.colorado.edu/hazards">
          <div class="icon nhc-icon">
            <?=$this->partial('nhc-svg.svg')?>
          </div>
          <span class="btn-txt">Natural Hazards Center</span>
        </a>
      </div>
    </div>
  </div>
</nav>

<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="well well-lg clearfix">
    <?=$this->render("search/searchbox.phtml")?>
  </div>
  <div class="about-us">
    <p>The Natural Hazards Center Library is a singular collection of hazards resources that focus on how society copes with natural hazards and catastrophic events. Our library houses a wide spectrum of information for both researchers and practitioners. Regardless of discipline, this extensive collection will provide practical, applied, and academic support to those in need of disaster knowledge.</p>
    <p>Anyone can search the library’s online catalog, which provides bibliographic access to the   collection, and direct access to hundreds of titles. In addition to   this online service, for a fee,   Library staff is available to conduct custom searches of the collection and answer other  hazards-related questions. We are happy to guide your research or put you in touch with   people or institutions that may have the answers you need.</p>
  </div>
</div>

<? $facetList = is_object($this->results) ? $this->results->getFacetList() : array(); ?>
<? //for some reason this is showing up even though I've turned it off in configurations, and cleared cache.  What gives? ?>
<? if (false && isset($facetList) && is_array($facetList)): ?>
  <div class="row">
    <? foreach ($facetList as $field => $details): ?>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
        <? $this->headScript()->appendFile('facets.js'); ?>
        <? $sort = isset($this->hierarchicalFacetSortOptions[$field]) ? $this->hierarchicalFacetSortOptions[$field] : ''; ?>
        <?
        $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <div class="facet <?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="all">
          </div>
        </div>
        <noscript>
      <? endif; ?>
      <? $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
      <div class="<?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
        <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
        <div class="row">
          <ul class="list-unstyled <?=$field == "callnumber-first" ? 'col-sm-6' : 'col-sm-12' ?>">
          <? /* Special case: two columns for LC call numbers... */ ?>
          <? if ($field == "callnumber-first"): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
              <? if (++$i == 10): ?>
                </ul><ul class="list-unstyled col-sm-6">
              <? endif; ?>
            <? endforeach; ?>
          <? /* Special case: collections */ ?>
          <? elseif ($field == 'hierarchy_top_title'): ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? else: ?>
                <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
              <? endif; ?>
            <? endforeach; ?>
          <? else: ?>
            <? $i = 0; foreach ($sortedList as $url => $value): ?>
              <? if (++$i > 10): ?>
                <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
                <? break; ?>
              <? elseif (!empty($value)): ?>
                <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
              <? else: $i--; ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endif; ?>
          </ul>
        </div>
      </div>
      <? if (isset($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
        </noscript>
      <? endif; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>