<hr/>
<div class="row">
    <div class="col-xs-4">
        <p><strong><a class="find-us" href="https://goo.gl/maps/iSsuxqhFtHm"><?=$this->transEsc('Find Us')?></a></strong></p>
        <p>
            Natural Hazards Library<br>
            483 UCB<br>
            Boulder, CO 80309<br>
            (303) 492-5787
        </p>
    </div>
    <!-- <div class="col-sm-4">
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
            <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
            <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
            <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
    </div> -->
    <div class="col-xs-4 col-xs-offset-4">
        <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
        <ul>
            <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
            <li><a href="mailto:hazctr@colorado.edu"><?=$this->transEsc('Ask a Librarian')?></a></li>
        </ul>
    </div>
</div>
